### ISSUE TITLE
데이터 형식 질문

### ISSUE THREAD

**Issue by young31** [DatathonInfo/H.D.A.I.2021#1]
받은 데이터 형식이 아래와 같이 설명과는 다른데
어떻게 처리해야 하는 건가요?

![image](https://user-images.githubusercontent.com/50350197/143531251-4f737b6d-e419-4492-9fc4-1f2f52582282.png)

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

주제 2 부정맥 진단 AI 모델 개발용으로 제공된 학습용 데이터 관련해서 곧 다시 공지드리겠습니다.

감사합니다.
H.D.A.I. 2021 운영팀.
