### ISSUE TITLE
[주제 2] 데이터 질문드립니다.

### ISSUE THREAD

**Issue by skarbs001** [DatathonInfo/H.D.A.I.2021#21]
안녕하세요.

다시 제공해주신 데이터 확인 중에  문의 사항이 있습니다.

현재 데이터셋 안에는 5_ 6_ 8_로 시작하는 xml 파일이 존재합니다.

해당 데이터를 열어보면,

6_ 으로 시작하는 데이터의 경우 5_, 8_로 시작되는 데이터(8개 리드)와 비교했을 때 리드 수(12개 리드)가 다릅니다.

아마도..? 데이터 포멧도 다르게되어 있는 것으로 생각됩니다.

여기서 문의사항이 있습니다.

1. 별도의 테스트셋으로 검증을 하실 것 같은데, 테스트 데이터에서는 6_ 시작하는 데이터(12개 리드)와 같은 유형의 파일이 존재하나요?

답변 부탁드립니다.
감사합니다.

**Comment by DatathonInfo** [comment]
안녕하세요. 
H.D.A.I. 2021 운영팀입니다.

1번 질문에 대한 답변은 "네 그렇습니다." 입니다. 

감사합니다.  
H.D.A.I. 2021 운영팀.
