### ISSUE TITLE
팀명확인

### ISSUE THREAD

**Issue by kohheekyung** [DatathonInfo/H.D.A.I.2021#43]
안녕하세요
주제1에 참가한 팀장 고희경 입니다. 
모델을 제출하려하는데 팀명을 확인할 수 있는 방법이 있을까요?

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

참가자님의 팀명은 **HeartUS**팀으로 확인되었습니다.

감사합니다.
H.D.A.I.2021 운영팀 드림
