### ISSUE TITLE
[주제2] 데이터 문의

### ISSUE THREAD

**Issue by skarbs001** [DatathonInfo/H.D.A.I.2021#5]
데이터 확인해 보니, 아래와 같은 구조로 되어있네요.

├───arrhythmia
│   ├───train
│   └───validation
└───normal
    ├───train
    └───validation

여기서 질문이 있습니다.

Train 데이터로 모델 학습하고, validation으로 평가해서 AUC를 측정하라는 의도로 보여집니다.
arrhythmia - validation (2232개) + normal -validation (2630) 데이터 = 4862개 데이터를 테스트해서 결과제출하면 되나요?

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

제공된 학습용 데이터 관련해서 곧 다시 공지드리겠습니다.

감사합니다.
H.D.A.I. 2021 운영팀.
