### ISSUE TITLE
[주제2. 심전도 데이터셋을 이용한 부정맥 진단 AI 모델] Task에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by sryim** [DatathonInfo/H.D.A.I.2021#6]
안녕하세요. 주제2 참가팀입니다.
주제2 목적이 부정맥 진단 AI 모델을 학습하는 것이라고 하셨는데 이에 대해 궁금한 점이 있어서 질문을 드리고자 합니다.
제공해주신 데이터에 여러 종류의 부정맥 label이 있다고 하셨는데, 이 label까지 정확히 예측하는 것인가요?
아니면 부정맥 subtype 과는 상관없이 부정맥인지 아닌지만 판단하면 되는 것인가요?
만약 부정맥 subtype까지 예측하는 것이라면 이 경우에 AUC를 어떻게 계산할지 조금 더 구체적으로 (micro/macro averaging 등) 말씀해주실 수 있으실까요?
감사합니다.

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

제공된 학습용 데이터 관련해서 곧 다시 공지드리겠습니다.

감사합니다.
H.D.A.I. 2021 운영팀.
