### ISSUE TITLE
주제1

### ISSUE THREAD

**Issue by penguin1109** [DatathonInfo/H.D.A.I.2021#73]
최종 순위결정에 있어서 A2C이미지와 A4C이미지에 부여하는 가중치가 다른가요?
Test data점수에 대해서만 결정되는건지 궁금합니다.
감사합니다

**Comment by DatathonInfo** [comment]
안녕하세요 참가자님,

A2C와 A4C 각각의 Score는 동일한 비율로 평가됩니다.
또한, 수상팀에 한해 코드 검증이 수행됩니다.

감사합니다.
H.D.A.I.2021 운영팀 드림
