### ISSUE TITLE
주제1

### ISSUE THREAD

**Issue by penguin1109** [DatathonInfo/H.D.A.I.2021#76]
결과는 내일 언제쯤 나올까요??
각자 개인 성적(?)은 알려주시는 건가요?

**Comment by DatathonInfo** [comment]
안녕하세요, 참가자님.

결과는 내일 오전 10:30에 공지 예정입니다.

주제 1의 경우 개별 성적은 별도로 안내해드리지 않습니다만
필요하신 경우 사무국 메일로 개별 문의 주시면 최대한 도움 드리도록 하겠습니다.

감사합니다.

HDAI 2021 사무국 배상.
